Fix concurrent map write fatal error.
Occurred on macOS due to use of a static map that got shared among all
reporters, but revealed a badly designed constructor for the reporter
which is refactored in this commit.

The fatal error that is fixed:

    fatal error: concurrent map writes

    goroutine 42 [running]:
    github.com/telepresenceio/telepresence/v2/pkg/client/scout.getInstallIDFromFilesystem({0x1061f0b68, 0xc0005edbc0}, 0xc0001f13b0, {0x1056c9d01, 0x3})
    	github.com/telepresenceio/telepresence/v2/pkg/client/scout/reporter.go:149 +0x7e5
    github.com/telepresenceio/telepresence/v2/pkg/client/scout.NewReporterForInstallType.func1(0xc0001f13b0)
    	github.com/telepresenceio/telepresence/v2/pkg/client/scout/reporter.go:186 +0x32

Signed-off-by: Thomas Hallgren <thomas@datawire.io>