Fix backward compatibility issue.
Agents <= 1.13.13/2.13.2 would fail with the message:

    error: appmounts '/tel_app_exports/echo-server/var/run/secrets/kubernetes.io' already exists

without the special handling of `/var/run/secrets` so this commit
reinstates a necessary part of it for those versions.

Signed-off-by: Thomas Hallgren <thomas@datawire.io>